services:
  shuffle1:
    build:
      context: .
      dockerfile: Dockerfile_1
    volumes:
      - .:/app
    container_name: shuffle1

  shuffle2:
    build:
      context: .
      dockerfile: Dockerfile_2
    volumes:
      - .:/app
    container_name: shuffle2

